import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#262155',
    minHeight: '100%',
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#262155',
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    paddingLeft: 50,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.51,
    shadowRadius: 13.16,
    elevation: 20,
  },
  saveText: {
    fontSize: 25,
    color: '#FCFFFF',
    fontFamily: 'Avenir-Medium',
  },
  selectedColor: {
    marginRight: 50,
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  activity: {
    flex: 1,
    height: 200,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    fontSize: 25,
    color: '#FCFFFF',
    fontFamily: 'Avenir-Medium',

  },
  colorContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  celeste: {
    margin: 20,
    backgroundColor: '#4CD964',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  green: {
    margin: 20,
    backgroundColor: '#FFCC00',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  lavander: {
    margin: 20,
    backgroundColor: '#007AFF',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  ny: {
    margin: 20,
    backgroundColor: '#FF9500',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  pink: {
    margin: 20,
    backgroundColor: '#FF2D55',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  candy: {
    margin: 20,
    backgroundColor: '#5856D6',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  lemon: {
    margin: 20,
    backgroundColor: '#FF3B30',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  crayola: {
    margin: 20,
    backgroundColor: '#5AC8FA',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 175,
    height: 69,
    backgroundColor: '#FD9F32',
    borderRadius: 10,
    shadowColor: '#000',
    margin: 30,
  },
});
