import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  textContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ECFFFE',
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    paddingLeft: 50,

  },
  selectedColor: {
    marginRight: 50,
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  activity: {
    flex: 1,
    fontSize: 25,
    height: 200,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
  },
  colorContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  aquamarine: {
    margin: 20,
    backgroundColor: '#60D394',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  green: {
    margin: 20,
    backgroundColor: '#AAF683',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  yellow: {
    margin: 20,
    backgroundColor: '#FFD97D',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  blue: {
    margin: 20,
    backgroundColor: '#717EC3',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  claret: {
    margin: 20,
    backgroundColor: '#7D1538',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  rose: {
    margin: 20,
    backgroundColor: '#F9E0D9',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  maya: {
    margin: 20,
    backgroundColor: '#7CC6FE',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  vivid: {
    margin: 20,
    backgroundColor: '#FF9B85',
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 175,
    height: 69,
    backgroundColor: 'rgba(30,191,178,1)',
    borderRadius: 25,
    shadowColor: '#000',
  },
});
