export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOAD_USER: 'LOAD_USER',
  LOAD_ACTIVITY: 'LOAD_ACTIVITY',
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  LOAD_USER_ACTIVITIES: 'LOAD_USER_ACTIVITIES',
  SUBMIT_TIME: 'SUBMIT_TIME',
  DELETE_ACTIVITY: 'DELETE_ACTIVITY',
};
